name: Build, Publish and Backup

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Packages
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Publish Project
        run: dotnet publish --configuration Release --output ./publish --no-build

      - name: Backup Published Files
        uses: actions/upload-artifact@v4
        with:
          name: Published-App
          path: ./publish

      # Example Deployment
      # Azure App Service
      # Hostinger VPS
      # FTP
      # SSH
